### PR TITLE
fix: use better positioning for the AnnotationTooltip caret and add maxWitdh to tooltip

### PR DESCRIPTION
**Pull request by ChitlangeSahas**
closes: #525
addresses: https://github.com/influxdata/ui/issues/1121

we realized that we need a way to handle the tooltip caret position, [issues:  #525, https://github.com/influxdata/ui/issues/1121]. This PR attempts to provide a solution. Following is a brief about of how how we ended up with this solution. 

First we thought that the issue in https://github.com/influxdata/ui/issues/1121 would be solved by limiting the width of the tooltip box. But we quickly realized that there are some edge cases (literally) which we don't think would be covered by just limiting the size of the tooltip.

For example, this annotation in the corner renders its caret, in between the two lines, because at it's current state its programmed to render the caret in the middle of the tooltip box.

image

To address this, one solution is to re-think the caret position. Currently, we position the caret in the center of the tooltip box, if we position it on top of the annotation line instead, we can handle those edge-case corner renders. This is what it looks like after the change:

Screen Shot 2021-04-06 at 10 49 03 PM

Screen Shot 2021-04-06 at 10 48 57 PM

In the UI with a long name:

Screen Shot 2021-04-08 at 10 54 57 AM

### CODE REVIEW

**Review by daviddkkim — APPROVED** [review]
@ChitlangeSahas 
you beautiful human being!

**Review by hoorayimhelping — APPROVED** [review]
Nice work dude! This is great.

We'll release once we get another commit that addresses 1121

**Comment by TCL735** [comment]
The top border of the tooltip looks cut off in Giraffe's storybook. May I suggest adjusting the margins in the `<PlotContainer>` that Giraffe uses in storybook to make this look cleaner?

Screen Shot 2021-04-08 at 11 36 42 AM

**Comment by TCL735** [comment]
Now becomes this with the adjustment 
Screen Shot 2021-04-08 at 11 44 03 AM

**Pull request merged**
