### PR TITLE
Add ability to update lat long based on table data

### PR DESCRIPTION
**Pull request by Palakp41**
Kapture 2020-12-09 at 13 55 09

### CODE REVIEW

**Review by hoorayimhelping — APPROVED** [review]

**Comment by hoorayimhelping** [comment]
@Palakp41 nice work!

If this functionality needs to be published before it can be used, we'll need to coordinate with @TCL735. I think there needs to be some additions to docs before the currently unpublished functionality in giraffe can be properly published

**Comment by Palakp41** [comment]
I don't think we need this published right away. We can wait a few days, we have more work going on in Giraffe that we might need later. Should we write docs about this GEO plot type?

**Comment by TCL735** [comment]
Maps doesn't have any docs.

**Comment by ivankudibal** [comment]
no giraffe component has docs

**Pull request merged**
